name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Composer install
      run: composer install
    - name: Create Docker network
      run: docker network create kikdev
    - name: Shutdown default MySQL
      run: sudo service mysql stop
    - name: Setup services
      run: docker-compose -f docker/docker-compose-services.yml up -d
      env:
        PASS: adminkik12
    - name: Sleep for 10 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'
    - name: Create test DB
      run: docker exec -i docker_mysql_1 mysql -uroot -padminkik12 -e "CREATE DATABASE test"
    - name: Fill test DB
      run: docker exec -i docker_mysql_1 mysql -uroot -padminkik12 test < tests/test.sql
    - name: Run tests
      run: docker run --net="kikdev" -v "$(pwd)":/opt/project --rm kiksaus/kikdev:latest /opt/project/vendor/bin/codecept run -c /opt/project/codeception.yml
