name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Composer install
      run: composer install
    - name: Create Docker network
      run: docker network create kikdev
    - name: Shutdown default MySQL
      run: sudo service mysql stop
    - name: Setup services
      run: PASS=adminkik12 docker-compose -f docker/docker-compose-services.yml up -d
    - name: Create test DB
      run: docker exec -i docker_mysql_1 mysql -uroot -h 127.0.0.1 -padminkik12 -e "CREATE DATABASE test"
    - name: Fill test DB
      run: docker exec -i docker_mysql_1 mysql -uroot -h 127.0.0.1 -ppadminkik12 test < tests/test.sql
    - name: Run tests
      run: docker run --net="kikdev" -v "$(pwd)":/opt/project --rm kiksaus/kikdev:latest /opt/project/vendor/bin/codecept run -c /opt/project/codeception.yml
